### PR TITLE
94 handle title template error

### LINKED ISSUE #94: Handle title template error
## Describe the bug

If the title template is missing, or has a render error blank title could be rendered

https://github.com/openmsupply/notify/blob/9238fc30a706aa219e3d1593c810ea980f7fbd95/backend/service/src/notification/enqueue.rs#L58

     `  log::error!("Failed to render notification template: {:?}", e);`

## To Reproduce

Steps to reproduce the behaviour:

### PR DESCRIPTION
**Pull request by jmbrunskill**
Closes #94

# 👩🏻‍💻 What does this PR do?
 

Creates an errored notification if a notification title template can't be rendered

### CODE REVIEW

File: backend/service/src/notification/enqueue.rs [hunk 1]
```diff
@@ -78,23 +63,57 @@ pub fn create_notification_events(
...
+                            error_message: Some(format!("{:?}", e)),
+                            ..base_row
+                        }
+                    }
+                }
+            }
+            None => base_row,
+        };
+
+        let notification_queue_row = match base_row_with_title.status {
```
Comment (jmbrunskill) [inline backend/service/src/notification/enqueue.rs:95]: I don't like how nested this ends up being. Maybe multiple `repo.insert_one` records is better than this base_row approach.
